[tool.poetry]
name = "blazetest-beta"
version = "2.2.6.dev310"
description = "Blazetest is a CLI tool to run your selenium tests faster and more effectively."
authors = ["Abrorjon Ruziboev <abror.ruzibayev@gmail.com>"]
readme = "README.md"
packages = [
    { include = "blazetest/" },
    { include = "blazetest/**/*.py" },
]
exclude = ["tests/*"]

[tool.poetry.dependencies]
python = ">=3.9,<=3.12.4"
click = ">=8.1.3"
pytest = ">=7.2.2"
PyYAML = ">=6.0"
toml = ">=0.10.2"
dacite = ">=1.8.0"
boto3 = ">=1.26.84"
licensing = ">=0.39"
pyopenssl = ">=23.0.0"
python-logging-loki = ">=0.3.1"
junitparser = "^3.2.0"
art = "^6.1"
docker = "^7.0.0"
tqdm = "^4.66.4"
allure-pytest = "^2.13.2"
allure-python-commons = "^2.13.2"

[tool.poetry.scripts]
blazetest = "blazetest.cli:cli"

[tool.poetry.group.dev.dependencies]
pytest-cov = "^4.1.0"
ruff = "^0.5.0"
pre-commit = "^3.7.1"
black = "^24.0.0"
flake8 = "^7.0.0"

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pyright]
venvPath = "."
venv = ".venv"
strict = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
