[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "runreporter"
version = "0.3.2"
description = "Library for logging runtime errors and sending execution reports via Telegram and Email"
authors = [{ name = "nosikmov" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "requests>=2.31.0"
]


