[project]
name = "casting-query-bot"
version = "0.1.1"
description = "Darcy Discord bot application"
requires-python = ">=3.13"
dependencies = [
    "cast-query",
    "casting-discord-framework",
    "casting-config",
    "llmgine",
    "litellm"
]

[dependency-groups]
dev = [
    "pytest>=8.3.0",
    "pytest-asyncio>=0.23",
    "pytest-dotenv>=0.5",
    "ruff>=0.8.0"
]
migrate = [
    "alembic>=1.13"
]
pipeline = [
    "dbt-core>=1.8"
]

[tool.uv.sources]
cast-query = { workspace = true }
casting-discord-framework = { workspace = true }
casting-config = { workspace = true }
llmgine = { workspace = true }

[project.scripts]
main = "casting.apps.casting_query_bot.__main__:package_main"

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "casting.apps.casting_query_bot"
namespace = true
