[project]
name = "nrl-sdk-lib"
version = "0.2.8"
description = "A library for working with the NRL SDK"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.13"
dependencies = ["pydantic>=2.11.7"]

[project.urls]
Homepage = "https://github.com/3lbits/nrl-sdk"
Documentation = "https://3lbits.github.io/nrl-sdk/"
Repository = "https://github.com/3lbits/nrl-sdk.git"
Issues = "https://github.com/3lbits/nrl-sdk/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/nrl_sdk_lib"]

[dependency-groups]
dev = [
    "anyio>=4.9.0",
    "deptry>=0.23.0",
    "pip-audit>=2.9.0",
    "poethepoet>=0.34.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "pytest-docker>=3.2.2",
    "pytest-mock>=3.14.1",
    "ruff>=0.11.11",
    "ty>=0.0.1a14",
]

[tool.ruff.lint]
select = ["ALL"]
# and then manually ignore annoying ones:
ignore = [
    #     "ANN401", # Any should be allowed
    "D211",
    "D213",
    "COM812",
    "D203",
    "ISC001",
    "PLC2401", # Allow non-ASCII characters
]
[tool.ruff.lint.per-file-ignores]
"src/nrl_sdk_lib/models/**/*.py" = [
    "E501", # Allow long lines in models
    "W505", # Allow long doc lines
]
"tests/**/*.py" = [
    # at least this three should be fine in tests:
    "S101",    # asserts allowed in tests...
    "ANN401",  # Any should be allowed
    "BLE001",  # Catch blind exception in tests should be allowed
    "PLR2004", # Magic values allowed in tests
]

[tool.ruff.lint.isort]
# so it knows to group first-party stuff last
known-first-party = ["src"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 122

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
omit = ["tests/*"]

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.deptry]
known_first_party = ["nrl_sdk_lib"]

[tool.poe.tasks]
format = "uv run ruff format"
lint = "uv run ruff check --fix"
check-types = "uv run ty check ."
check-deps = "uv run deptry ."
audit = "uv run pip-audit --ignore-vuln GHSA-4xh5-x5gv-qwph"
test = "uv run pytest --doctest-modules -s --cov --cov-report=term-missing --cov-report=html"
release = ["lint", "check-types", "check-deps", "audit", "test"]
