[project]
name = "notion-py-client"
version = "0.1.7"
description = "A Python client for Notion API"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.11.10",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
authors = [
    { name = "Masafumi Higashi", email = "cruiseeast@gmail.com" }
]
[project.urls]
Homepage = "https://higashi-masafumi.github.io/notion-py/"
Repository = "https://github.com/higashi-masafumi/notion-py"
Issues = "https://github.com/higashi-masafumi/notion-py/issues"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
