[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "balathon"
version = "0.0.4"
description = "A Python package that retrieves code snippets by number"
readme = "README.md"
license = {text = "MIT"}
authors = [{name = "Balathon"}]

[tool.setuptools.package-data]
"balathon" = ["codes/*.txt"]
