[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
include = ["tennetsac*"]

[tool.setuptools.package-data]
tennetsac = [
    "utils/smi_ted_light/*.txt",
    "ckpt_files/*.ckpt",
    "ckpt_files/fine-tuned/*.ckpt"
]

[project]
name = "tennetsac"
version = "0.1.4"
description = "Thermodynamics-embedded Neural Network for Segment Activity Coefficients"
authors = [{ name="Yue Yang" }]
readme = "README.md"
license = { file = "MIT" }
requires-python = ">=3.9"

dependencies = [
    "jupyterlab",
    "matplotlib",
    "numpy>=1.26.4",
    "pandas",
    "torch>=2.1.2",
    "scikit-learn",
    "scipy",
    "torchaudio",
    "torchvision",
    "tqdm",
    "rdkit",
    "transformers==4.36.2",
    "safetensors",
    "tokenizers",
    "accelerate"
]

