[project]
name = "library_and_tools"
version = "1.0.0"
description = "Ziad Library for drawing, reading files, and more. Enjoy!ğŸ’"
authors = [
    { name = "zeyad", email = "zayedzezo82@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.7"

# Ù„Ùˆ ÙÙŠÙ‡ Ù…ÙƒØªØ¨Ø§Øª   ØªØ§Ù†ÙŠØ© Ø¨ØªØ­ØªØ§Ø¬Ù‡Ø§ Ù…ÙƒØªØ¨ØªÙƒØŒ Ø¶ÙŠÙÙ‡Ø§ Ù‡Ù†Ø§
dependencies = []

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"