[project]
name = "strava-activity-mcp-server"
version = "0.1.3"
description = "Trying to implement environment variables for client_id"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "build>=1.3.0",
    "mcp[cli]>=1.16.0",
    "twine>=6.2.0",
]

[project.scripts]
strava-activity-mcp-server = "strava_activity_mcp_server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
