[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chess-tournament"
version = "0.2.13"
description = "A chess tournament software in Python"
authors = [
    { name = "Thi26", email = "thiiicroon@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "jinja2>=3.1",
    "flake8",
    "flake8-html"
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Topic :: Games/Entertainment :: Board Games",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.optional-dependencies]
dev = [
    "jinja2>=3.1",
    "black",
    "flake8",
    "flake8-html",
    "pytest",
    "pytest-html",
    "pre-commit"
]

[project.scripts]
chess = "chess.main:main"

[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"chess" = ["data/*.json"]


[tool.flake8]
max-line-length = 88
ignore = ["E203", "W503"]
exclude = [
    ".git",
    "__pycache__",
    "venv",
    ".venv",
    ".cache",
    "build",
    "dist",
    "migrations",
]
show-source = true
statistics = true

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-v --maxfail=3 --disable-warnings"
testpaths = ["tests"]
pythonpath = ["src"]
