[tool.poetry]
name = "vpp-vrouter"
version = "0.1.29"
description = "USDN vRouter with VPP"
authors = ["Filip Gschwandtner <filip.gschwandtner@pantheon.tech>", "Phan Dang <phan.dang@usdatanetworks.com>"]
packages = [
    {include = "vpp_vrouter", from = "."},
]
readme = "README.md"
license = "US Data Networks. All rights reserved."

[tool.poetry.dependencies]
python = "^3.10"
dataclasses-json = "^0.5.7"
jsonrpclib = "^0.2.1"
marshmallow = "^3.20.0"
marshmallow-dataclass = "^8.6.0"
marshmallow-enum = "^1.5.1"
mypy-extensions = "^1.0.0"
numpy = "^1.26.0"
packaging = "^24.0"
Pyro5 = "^5.15"
pyroute2 = "^0.8.0"
serpent = "^1.41"
sudo = "^1.0.0"
typing-inspect = "^0.9.0"
typing-extensions = "^4.15.0"
vpp-papi = "^2.3.0"
python-json-logger = "^3.0.0"

[tool.poetry.group.dev.dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
vrouter = "vpp_vrouter.server.server:cli"
