[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lunofetch"
version = "2.0.3"
description = "A lightweight Neofetch-like system info tool with custom ASCII logo support."
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
  {name = "B. Tharun Bala", email = "your_email@example.com"},
]
keywords = ["system", "neofetch", "terminal", "ascii", "linux"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX :: Linux",
  "Topic :: System :: Monitoring"
]

dependencies = [
  "psutil",
  "distro"
]

[project.scripts]
lunofetch = "lunofetch.lunofetch:main"
