[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "simplesitesearch"
dynamic = ["version"]
description = "Reptile Simple Site Search django app"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Reptile Tech", email = "flouis@reptile.tech"},
]
maintainers = [
    {name = "Reptile Tech", email = "flouis@reptile.tech"},
]
keywords = ["django", "search", "cms", "django-cms"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Framework :: Django",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.0",
    "Framework :: Django :: 4.1",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.0",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.6"
dependencies = [
    "Django>=3.2",
    "django-cms>=3.2",
    "requests>=2.25.0",
]

[project.urls]
Homepage = "https://github.com/reptiletech/simplesitesearch"
Documentation = "https://github.com/reptiletech/simplesitesearch#readme"
Repository = "https://github.com/reptiletech/simplesitesearch.git"
"Bug Tracker" = "https://github.com/reptiletech/simplesitesearch/issues"

[tool.setuptools]
packages = ["simplesitesearch"]
include-package-data = true

[tool.setuptools.package-data]
simplesitesearch = ["templates/simplesitesearch/*.html"]


