[tool.poetry]
name = "optibioseq"
version = "0.2.0"
description = ""
authors = ["Ivan Corona Guerrero <icg.microbiologia@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
openpyxl = "^3.0.9"
pandas = "^1.4.0"
numpy = "^1.22.2"
bs4 = "^0.0.1"


[tool.poetry.dev-dependencies]
pytest = "^5.2"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
