[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "autofuzzts"
version = "0.1.0"
description = "Automated fuzzy time series forecasting library"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Jan Timko", email = "jantimko16@gmail.com" }]
requires-python = ">=3.11"

dependencies = [
    "numpy>=1.26.0",
    "pandas>=2.2.0",
    "scikit-learn>=1.5.0",
    "scipy>=1.15.0",
    "xgboost>=3.0.0",
    "lightgbm>=4.6.0",
    "tpot>=1.0.0",
    "optuna>=4.3.0",
    "matplotlib>=3.10.0",
    "seaborn>=0.13.0",
    "requests>=2.32.0",
    "PyYAML>=6.0.0",
    "joblib>=1.4.0",
    "tqdm>=4.67.0"
]

[project.urls]
"Homepage" = "https://github.com/jtimko16/AutoFuzzTS"
"Bug Tracker" = "https://github.com/jtimko16/AutoFuzzTS/issues"

[tool.setuptools.packages.find]
exclude = ["tests*", "notebooks*", "schema*"]