[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

#[tool.setuptools]
#packages = [
#  "dancer",
#]
#include-package-data = true
#package-dir = {"" = "src"}

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"dancer._styling" = [
    "colored_transcription_guide.qst",
    "STYLING.md"
]
"dancer._styling.styles" = [
    "base.qst",
    "colored_cherry_blossom.qst",
    "colored_evening_sky.qst",
    "colored_red_rage.qst",
    "colored_summer_sky.qst",
    "default_dark.qst",
    "default_light.qst",
    "high_contrast.qst",
    "thick_dark.qst",
    "thick_light.qst",
    "thin_dark.qst",
    "thin_light.qst",
    "thin_light_blue.qst",
    "thin_light_burgundy.qst",
    "thin_light_dark.qst",
    "thin_light_green.qst",
    "thin_light_purple.qst",
]
"dancer._styling.themes" = [
    "adalfarus_base.qth",
    "adalfarus_chisled.qth",
    "adalfarus_default.qth",
    "adalfarus_high_contrast.qth",
    "adalfarus_modern.qth",
    "adalfarus_thick.qth",
    "adalfarus_thick_basic.qth",
    "adalfarus_thin.qth",
    "adalfarus_thin_basic.qth",
]

[project]
name = "dncer"  # Temp name until dancer becomes available
version = "0.0.1.0b0"
dependencies = ["packaging", "typing_extensions", "requests", "aplustools[all]~=2.0.0.0"]
requires-python = ">= 3.10"
authors = [
  {name = "Cariel Becker", email = "cariel.becker@gmx.de"},
]
maintainers = [
  {name = "Cariel Becker", email = "cariel.becker@gmx.de"},
]
description = "An app framework"
readme = {file = "README.md", content-type = "text/markdown"}
license = "LGPL-2.1-or-later"
keywords = ["general", "tools", "app tools", "production", "apt"]
classifiers = [
	"Development Status :: 1 - Planning",
	"Programming Language :: Python",
	"Natural Language :: English"
]

[project.optional-dependencies]
qt = ["PySide6>=6.7.0"]
dev = ["pytest"]

[project.urls]
Home = "https://pypi.org/project/dancer/"
Repository = "https://github.com/adalfarus/dancer"
Documentation = "https://github.com/adalfarus/dancer/wiki"
"Issue tracker" = "https://github.com/adalfarus/dancer/issues"

#[tool.pytest.ini_options]
## This is equivalent to setup_requires and tests_require
## Add your pytest configuration here
#addopts = "your pytest options"
