[tool.poetry]
name = "gemini-application"
version = "0.3.2"
description = "Core application library of the GEMINI Digital Twin"
authors = [ "Ryvo Octaviano <ryvo.octaviano@tno.nl>",
    "Leila Hashemi <leila.hashemi@tno.nl>",
    "Demetris Palochis <demetris.palochis@tno.nl>",
    "Arturs Blinovs <arturs.blinovs@we-p.nl>"
]
readme = "README.md"
packages = [{include = "gemini_application"}]
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development"
]
homepage = "https://nwn.nu/projecten/innovaties/datagedreven-optimalisatie-aardwarmte-systemen/"
documentation = "https://readthedocs.org"
repository = "https://github.com/GEMINI-Digital-Twin/gemini-model"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.2.2"
pytest-cov = "^5.0.0"
flake8 = "^7.0.0"
gemini-framework = "0.3.2"
chromadb = "^1.0.12"
langchain-community = "^0.3.27"
ollama= "^0.5.1"
lasio = "^0.31"
ruptures = "^1.1.9"
pypdf = "^5.7.0"
langchain-openai = "0.3.28"
flake8-docstrings = "^1.7.0"

[tool.flake8]
ignore = ["W503", "W504", "E127", "E128"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"