[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
[project]
name = "automod"
version = "0.0.2"
authors = [
  { name="Elina HeikkilÃ¤", email="elina.s.heikkila@aalto.fi" },
]
description = "Automated modification and crossover placement for the design of curved DNA origami structures."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "PySide6",
    "numpy",
    "scipy",
]

[project.urls]
Homepage = "https://github.com/AutoMod-DNA/automod"
Issues = "https://github.com/AutoMod-DNA/automod/issues"

[project.scripts]
automod = "automod.automod:main"
