[tool.ruff]
exclude = [
  "__pycache__",
  ".idea",
  ".vscode",
  "build",
  "contrib",
  "dist",
  "doc",
  ".?venv3?",
  "venv3?",
]
line-length = 79
target-version = 'py39'

[project]
name = "djali"
version = "0.5.0"
description = "Key/Value Database Clients"
authors = [{ name = "doubleO8", email = "wb008@hdm-stuttgart.de" }]
license = "GPL-2.0-only"
readme = "README.md"
#homepage = "https://sourceforge.net/projects/djali/"
requires-python = ">=3.9.2"

dependencies = ["cloudant~=2.12.0", "six>=1.13.0", "boto3>=1.18.21"]

[dependency-groups]
dev = [
  "pre-commit~=4.2.0",
  "pytest~=8.4.1",
  "ruff~=0.12.0",
  "sphinxcontrib-napoleon~=0.7",
  "Sphinx~=4.5.0",
  "sphinx-rtd-theme~=1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["djali"]

[tool.hatch.build.targets.wheel]
include = ["djali"]
