[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "katmlutils"
version = "0.1.1"
description = " This is a package that keeps all the Machine learning Utils in the Software Team."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.9"
license = {text = "MIT"}
authors =[{name = "SARAO MLOps", email = "saraomlops@gmail.com"}]
dependencies = ["lst-pressure==1.8.6"]
keywords = ["machine learning", "utils"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[projects.url]
Homepage = "https://github.com/ska-sa/katmlutils"
Issues = "https://github.com/ska-sa/katmlutils/issues"

[project.scripts]
mlutils = "katmlutils.utils:main"

[tool.hatch.build.targets.wheel]
packages = ["src/katmlutils"]