[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "callme-marck"         # must be unique on PyPI
version = "6.8.0"
description = "A simple package that just says 'You called me!'"
authors = [
    { name = "Marck Munoz", email = "you@example.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
keywords = ["example", "callme"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]

[project.urls]
Homepage = "https://github.com/yourusername/callme"
