[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jshep-tri-template-deployment"
version = "0.0.4"
authors = [
  { name="John Shepherd", email="john.shepherd@tri.global" },
]
description = "A small example Python package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/jshep-tri/template-deployment-repo"
Issues = "https://github.com/jshep-tri/template-deployment-repo/issues"
