[build-system]
requires = ["setuptools>=69", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "wiki2crm"
version = "0.1.3"                     
description = "Tools to convert Wikidata to CIDOC CRM (eCRM/LRMoo/INTRO)"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [{ name = "Laura Untner" }]
dependencies = ["rdflib", "requests", "tqdm", "pyshacl"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["wiki2crm"]
license-files = ["LICENSE.txt"]

[tool.setuptools.package-data]
"wiki2crm" = ["shapes/**/*.ttl"]

[project.scripts]
wiki2crm = "wiki2crm.cli:main"