[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "asodesigner"
version = "1.1.3"
description = "Feature extraction and analysis toolkit for antisense oligonucleotide design."
readme = "README.md"
requires-python = ">=3.9,<3.13"
authors = [
    { name = "TAU-Israel iGEM Team" }
]
keywords = ["antisense", "oligonucleotide", "bioinformatics", "igem"]
dependencies = [
    "numpy>=1.26,<2.3",            # manylinux wheels exist (allows 2.2.x)
    "pandas>=2.2,<2.3",            # avoids 2.3.x source build on your box
    "scipy>=1.11,<1.12",           # wheels available for Py3.10
    "matplotlib",
    "numba",
    "biopython",
    "ViennaRNA",
    "primer3-py",
    "gffutils",
    "codon-bias",
    "fuzzysearch",
    "tqdm",
    "multiprocess",
    "gget",
    "mega.py",
    "xgboost>=2.0",
    "scikit-learn>=1.5",
    "gdown>=5.1.0",
    "pysam"
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

[project.urls]
"Homepage" = "https://2025.igem.wiki/tau-israel/home"

[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["asodesigner", "asodesigner.*"]
exclude = ["tests*"]

[tool.setuptools.package-data]
asodesigner = [
  "model.json",
  "features/rna_access/output/stub",  # ‚Üê stub is a file
]

"asodesigner.populate.cai_cache" = ["weights_cache.json"]

[tool.setuptools.exclude-package-data]
asodesigner = [
  "off_target/index_structure/**",
  "**/__pycache__/**",
]
