[build-system]
requires = ["setuptools>=75", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mynotes-cli"
version = "0.3.2"
description = "CLI notes manager with tags, colored output, exports and shell autocompletion"
authors = [{ name = "Antonín Šiška", email = "your.email@example.com" }]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]

requires-python = ">=3.8"
dependencies = ["rich>=13", "argcomplete>=3"]

keywords = ["notes", "cli", "terminal", "tags", "productivity", "python"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Utilities"
]

[project.urls]
Homepage = "https://github.com/antoninsiska/mynotes"
Repository = "https://github.com/antoninsiska/mynotes"
Issues = "https://github.com/antoninsiska/mynotes/issues"

[project.scripts]
mynotes = "mynotes.cli:main"

[tool.setuptools.packages.find]
include = ["mynotes*"]