[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "r2d2Audio"
version = "0.2.0"
description = "LibrerÃ­a experimental que convierte texto en tonos tipo R2-D2."
readme = "README.md"
authors = [
  { name="Edinson Tunjano", email="juanmadiaz108@gmail.com" }
]
license = { text = "MIT" }
keywords = ["r2d2", "r2d2Audio"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "scipy"
]

requires-python = ">=3.8"