[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pytest-dataguard"
version = "1.0.3"
description = "Data validation and integrity testing for your datasets using pytest."
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Ola Austine", email = "austineolanrewaju@gmail.com" }]
keywords = ["pytest", "plugin", "data", "quality", "csv", "polars"]
classifiers = [
  "Framework :: Pytest",
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dependencies = [
    "pip>=25.2",
    "polars>=1.34.0",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
]

[project.urls]
Homepage = "https://github.com/olaaustine/pytest_dataguard"
Issues = "https://github.com/olaaustine/pytest_dataguard/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points.pytest11]
dataguard = "pytest_dataguard.options"
