# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Thanks for opening your first issue here! ğŸ’–
# Comment to be posted on PRs from first time contributors in your repository
newPRWelcomeComment: |
  Thanks for opening this pull request! ğŸ’–
# Comment to be posted on PR merges from first time contributors in your repository
firstPRMergeComment: |
  Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰
  We are proud of you and your accomplishment ğŸ†.

  ![thanks-for-pr-image](https://github.com/user-attachments/assets/dca6332b-fce5-4002-917b-1b695c4029bd)
