[build-system]
requires = [ "hatchling==1.27.0", "hatch-vcs==0.5.0",]
build-backend = "hatchling.build"

[project]
name = "pyiron_snippets"
description = "pyiron_snippets - Short, dependency-free python snippets."
readme = "docs/README.md"
keywords = [ "pyiron",]
requires-python = ">=3.11, <3.15"
classifiers = [ "Development Status :: 5 - Production/Stable", "Topic :: Software Development", "Topic :: Scientific/Engineering", "License :: OSI Approved :: BSD License", "Intended Audience :: Developers", "Intended Audience :: Science/Research", "Operating System :: OS Independent", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.13", "Programming Language :: Python :: 3.14",]
dependencies = []
dynamic = [ "version",]
[[project.authors]]
name = "Liam Huber"
email = "liamhuber@greyhavensolutions.com"

[[project.authors]]
name = "Sam Waseda"
email = "o.waseda@mpie.de"

[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/pyiron/pyiron_snippets"
Documentation = "https://pyiron-snippets.readthedocs.io"
Repository = "https://github.com/pyiron/pyiron_snippets"

[project.optional-dependencies]
tests = [ "cloudpickle==3.1.1",]

[tool.ruff]
exclude = [ "docs", "notebooks", "setup.py", "_version.py",]

[tool.black]
extend-exclude = "(\n  ^/docs\n)\n"

[tool.mypy]
exclude = [ "^docs/conf\\.py$", "^tests/",]
ignore_missing_imports = true
strict_equality = true
non_interactive = true
install_types = true

[tool.hatch.build]
include = [ "pyiron_snippets",]

[tool.hatch.version]
source = "vcs"
path = "pyiron_snippets/_version.py"

[tool.ruff.lint]
select = [ "E", "F", "UP", "B", "SIM", "I",]
ignore = [ "E501",]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [ "F401",]

[tool.hatch.build.hooks.vcs]
version-file = "pyiron_snippets/_version.py"

[tool.hatch.build.targets.sdist]
include = [ "pyiron_snippets",]

[tool.hatch.build.targets.wheel]
packages = [ "pyiron_snippets",]
