[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aasman"
version = "0.2.1.95"
description = "A sample Python package for testing"
readme = "README.md"
authors = [
  { name = "Đỉnh Lưu Aasman", email = "luulacdinh.hp2021@gmail.com" }
]
license = {text = "MIT"}
requires-python = ">=3.7"
dependencies = []

[project.urls]
"Homepage" = "https://github.com/LuuLacDinh/aasman"
"Bug Tracker" = "https://github.com/LuuLacDinh/aasman"