[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "galgopy"
version = "0.1.1"
dependencies = [ "numpy" ]
requires-python = ">=3.11"
authors = [{ name = "vec2pt" }]
maintainers = [{ name = "vec2pt" }]
description = "Basic implementation of a genetic algorithm (GA)."
readme = { file = "README.md", content-type = "text/markdown" }
license = "MIT"
keywords = ["optimization", "genetic-algorithm", "ga", "algorithm"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.optional-dependencies]
test = ["pytest"]
dev = ["ruff"]

[project.urls]
Homepage = "https://github.com/vec2pt/galgopy"
Repository = "https://github.com/vec2pt/galgopy.git"
Issues = "https://github.com/vec2pt/galgopy/issues"
# Changelog = "https://github.com/vec2pt/galgopy/blob/master/CHANGELOG.md"

[tool.pytest.ini_options]
testpaths = ["tests"]


[tool.ruff]
line-length = 80
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true

[tool.ruff.lint]
select = [
    "ANN", # flake8 type annotations
    "B", # flake8-bugbear
    "D", # pydocstyle
    "E", # pycodestyle
    "F", # Pyflakes
    "I", # isort
    "RUF", # ruff-specific rules
    "SIM", # flake8-simplify
    "UP", # pyupgrade
]
ignore = ["ANN101", "D105", "ANN002", "ANN003"]
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["ANN","D"]
