[project]
name = "nothing-less"
version = "0.6.0"
description = "A TUI paging application with enhanced support for tabular data and real-time streaming"
authors = [
    {name = "Matt Pryor",email = "mapryor1991@yahoo.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "textual>=0.55.0",
    "pyperclip (>=1.11.0,<2.0.0)",
]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/mpryor/nothing-less"
Issues = "https://github.com/mpryor/nothing-less/issues"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
nless = "nless.cli:main"

[tool.poetry.group.dev.dependencies]
textual-dev = "^1.7.0"
pre-commit = "^4.3.0"

[tool.poetry]
packages = [
    {include="nless"}
]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.6.0"
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
version_files = ["pyproject.toml:^version"]
