[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "a3dgamemaker"
version = "0.0.8"
description = "create a 3d game in 10 lines (without map)"
authors = [
  { name="delogstudio", email="3bth5550@gmail.com" }
]
license = { text = "Proprietary" }
dependencies = []
