[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "shipaw"
version = "0.3.20"
description = "Shipping client"
authors = [
    { name = "pawrequest", email = "shipaw+pawrequest@users.noreply.github.com" }
]
license = "MIT"

readme = "README.md"
requires-python = ">= 3.13"
dependencies = [
    "apc-hypaship>=0.1.8",
    "parcelforce-expresslink>=0.1.7",
    "pawdf>=0.1.0",
    #
    "httpx>=0.28.1",
    "pygments>=2.19.2",
    "pydantic[email]>=2.11.9",
    "pytest>=8.4.2",
    "fastapi[standard]>=0.117.1",
    "jinja2>=3.1.6",
    "hatchling>=1.27.0",
    "combadge[zeep]>=4.8.2",
    "loguru>=0.7.3",
    "thefuzz>=0.22.1",
    "pydantic-extra-types>=2.10.5",
    "pydantic-settings>=2.11.0",
    "phonenumbers>=9.0.15",
]


[project.urls]
Homepage = "https://github.com/pawrequest/shipaw"

[dependency-groups]
dev = [
    "autodoc-pydantic>=2.2.0",
    "myst-parser>=4.0.1",
    "sphinx>=8.2.3",
    "sphinx-autodoc-typehints>=3.2.0",
    "sphinx-readme>=1.2.1",
    "sphinx-rtd-dark-mode>=1.3.0",
    "sphinx-rtd-theme>=3.0.2",
]


[tool.ruff]
line-length = 120
extend-select = ["Q", "RUF100", "UP"]
flake8-quotes = { inline-quotes = "single", multiline-quotes = "double" }
format.quote-style = "single"

#[tool.uv.sources]
# GIT
#pawdantic = { git = 'https://github.com/pawrequest/pawdantic' }
#pawdf = { git = 'https://github.com/pawrequest/pawdf' }
#royal-mail-click-and-drop = { git = 'https://github.com/pawrequest/royal-mail-click-and-drop' }
#parcelforce-expresslink = { git = 'https://github.com/pawrequest/parcelforce_expresslink' }
#apc-hypaship = { git = 'https://github.com/pawrequest/apc-hypaship' }

[tool.uv.build-backend]
source-includes = ["src/shipaw/ui/**"]

#[tool.uv]
#package = true