[project]
name = "pydantic-firebase-remoteconfig"
version = "0.1.0"
description = "A simple Firebase Remote Config binding for Pydantic"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-auth>=2.41.1",
    "google-auth-httplib2>=0.2.0",
    "httpx>=0.28.1",
    "pydantic[email]>=2.11.10",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "ruff>=0.13.3",
]

[tool.hatch.build.targets.wheel]
packages = ["pydantic_firebase_remoteconfig"]

[tool.mypy]
ignore_missing_imports = true
plugins = ['pydantic.mypy']
