# === GENERAL RUN PARAMETERS ===
# Email address required for Entrez queries
entrez_login: "thedoudnalab@gmail.com"
# Default thread number for processing in this and associated SMK pipeline
threads: 20
# Run name | the run names must follow the naming standard:
# <mode>_<date>_<medit_version>
# ::mode:: -> At the current version this can be either: 'default' or 'private'
# ::date:: -> MMDDYY
# ::medit_version:: -> current is v0
run_name: "private_121123_v0"
# Must be the same as specified for the run_name
processing_mode: 'private'

# == RUN PARAMETERS ==
qtype: 'hgvs'
BEmode: 'off'
editor: 'clinical'

# This needs to be implemented through mEdit.py
editor_list: []

# === I/O PATHS ===
# == DIRECTORIES ==
# Canonical storage folder for FASTA References
fasta_root_path: "/groups/clinical/projects/clinical_shared_data/genomes/pkl"
# Parent output directory where files should be stored after processing
output_directory: "/groups/clinical/projects/medit_analysis"
#
db_path: "/groups/clinical/projects/medit_database"
# Directory that holds the query HGVSs
variant_query_dir: "/groups/clinical/projects/medit_analysis/input_queries/coord_queries.csv" #"/groups/doudna/projects/daniel_projects/editability/jobs/query" # "/groups/clinical/projects/editability/medit_queries/medit_test/test_in"

# == FILENAMES ==
# Outputs
gene_report: "Gene_Report.csv"
variant_report: "Variant_Report.csv"
be_report: "BaseEditors_found.csv"

# Path where downloaded references are temporarily stored
#fasta_download_path: "/groups/clinical/projects/clinical_shared_data/hprc/aws2"
# Intermediate path where compression routine temporaries are saved
#fasta_compressed_path: "/groups/clinical/projects/clinical_shared_data/hprc/bgzipped_fasta"

# === DOWNLOAD PARAMETERS ===
aws_url: "https://s3-us-west-2.amazonaws.com/human-pangenomics/working/HPRC/"
aws_path: "assemblies/year1_freeze_assembly_v2/assembly_qc/dipcall_v0.2"
filename_suffix: "f1_assembly_v2.pair"
vcf_id: ["PG_WGS_HG38"]

# === FILE PREFIXES ===
# Reference genome prefix
sequence_id: ["hg38",]#"NA18906.paternal"]#, "HG03453.maternal", "NA18906.paternal"]


# The genomic window to be opened on each side of a gene harboring a variant of interest
#window_size: 1000
