# === GENERAL RUN PARAMETERS ===

# Default thread number for processing in this and associated SMK pipeline
threads: 1
# Run name | the run names must follow the naming standard:
# <date>_<medit_version>
# ::date+time:: -> YYMMDDHHMMSSf
# ::random alphanumeric:: -> 9m7aQ0KRZx
run_name: ""
# Run's main directory
output_directory: ""
# Must be the same as specified for the run_name
processing_mode: ""
# mEdit can process more than one query file at a time
#   This index keeps track of the possible different query processing branches
query_index: ""

# == RUN PARAMETERS ==
# Any applicable defaults are defined at prog/arguments.py
qtype: ""
be_request: ""
editor_request: ""
distance_from_cutsite: ""
# Custom editor parameters required according to prog/arguments.py
pam: ""
guide_length: ""
pam_is_first: ""
dsb_position: ""
editing_window:
  - 4
  - 8
target_base: ""
result_base: ""

# === I/O PATHS ===
# == DIRECTORIES ==
# Directory that holds the query HGVSs
variant_query: ""

# Parent database folder
support_tables: ""

# Path to Log file
logfile_path: ""

# == TABLE FORMATING
# == Define the columns in *_Guide_differences tables that need to be transformed into float type
#       at the aggregation step
float_cols: ['Alt CBE Score', 'Alt ABE score',
             'Alt Azimuth Score', 'Alt DeepCas9 Score',
             'Alt DeepCpf1 Score', 'Alt OOF Score']

# Path to BEs / Editor libraries
# * Set values are the standard options. However, the --custom_batch option may change these
editors: "editors.pkl"
base_editors: "base_editors.pkl"
# === Local Configuration Sources ===
models_path: "models"

# === DOWNLOAD PARAMETERS ===
aws_url: "https://s3-us-west-2.amazonaws.com/human-pangenomics/working/HPRC"
aws_path: "assemblies/year1_freeze_assembly_v2/assembly_qc/dipcall_v0.2"
vcf_filename: "hprc-v1.1-combined-phased.filtered"
#filename_suffix: "f1_assembly_v2.dip"
vcf_id: ["HG00438", "HG00621", "HG00673", "HG00733", "HG00735", "HG00741", "HG01071", "HG01106", "HG01109", "HG01123", "HG01175", "HG01243", "HG01258", "HG01358", "HG01361", "HG01891", "HG01928", "HG01952", "HG01978", "HG02055", "HG02080", "HG02109", "HG02145", "HG02148", "HG02257", "HG02486", "HG02559", "HG02572", "HG02622", "HG02630", "HG02717", "HG02723", "HG02818", "HG02886", "HG03098", "HG03453", "HG03486", "HG03492", "HG03516", "HG03540", "HG03579", "NA18906", "NA20129", "NA21309"]
