[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyweboverlay"
version = "1.0.3"
description = "A Python package for creating simple local web overlays for streams and other needs"
readme = "README.md"
authors = [{ name = "chrisrca" }]
license = { file = "LICENSE" }
requires-python = "==3.9.*"
dependencies = [
    "Flask==3.1.2",
    "flask-socketio==5.3.6",
    "requests==2.32.5",
]
keywords = ["overlay", "web", "obs"]
classifiers = [
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools]
packages = ["pyweboverlay"]

[project.urls]
Repository = "https://github.com/chrisrca/pyweboverlay"