[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kn-fancy-pack"
version = "0.1.1"
description = "A tiny guessing-game utility with a friendly API and CLI"
authors = [
  {name = "Norbi Kukta", email = "noreply@example.com"}
]
dependencies = []
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
startguess = "kn_fancy_pack.cli:main"
