name: Sphinx Build and Deploy

on:
  workflow_dispatch:
  pull_request:
    types:
      - review_requested
      - closed
    branches:
      - beta
    paths:
      - doc/**
      - .github/workflows/sphinx.yml

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/configure-pages@v5
      - uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - name: Install Library and Build HTML
        run: |
          echo "::group::Install Library"
          uv sync --no-default-groups --group doc
          echo "::endgroup::"

          echo "::group::Build HTML"
          uv run sphinx-build doc/source doc/build/html -D release=$(uv version --short)
          echo "::endgroup::"

      - name: Fix permissions
        run: |
          chmod -c -R +rX "doc/build/html/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload artifact
        if: |
          github.event_name == 'workflow_dispatch' ||
          (github.event_name == 'pull_request' && github.event.action == 'closed')
        uses: actions/upload-pages-artifact@v4
        with:
          path: doc/build/html

  deploy:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.action == 'closed')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: sphinx-build
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
