[build-system]
requires = ["maturin>=1.2,<2"]
build-backend = "maturin"

[project]
name = "suma_ulsa"
version = "0.1.10"
description = "Sistema Universitario de Métodos Académicos (SUMA) - librería Python con backend en Rust"
authors = [
    { name="Ari Castillo", email="castilloari282@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

[tool.pyright]
include = [
    "suma_ulsa"
]
exclude = [
    "**/build",
    "**/target", 
    "**/venv",
    "**/__pycache__"
]
reportMissingImports = false
reportMissingModuleSource = false

[tool.mypy]
plugins = []
follow_imports = "silent"
ignore_missing_imports = true