[build-system]
requires = ["flit_core>=3.4"]
build-backend = "flit_core.buildapi"


[project]
name = "simpliflow"
version = "0.2.1"
authors = [
  { name="Deven Panchal", email="devenrpanchal@gmail.com" },
]
description = "simpliflow:  An Open Source Modular Framework to quickly create, deploy, orchestrate Generative AI Agents and Agentic workflows and integrate into business applications."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]



dependencies = [
  "litellm",
  "anthropic",
  "qiskit",
  "matplotlib",
  "qiskit-ibm-runtime",
  "python-dotenv",
  "requests",
  "openai",
  "cohere"
]

[project.urls]
Homepage = "https://devenpanchal.github.io/simpliflow-website/"
Documentation = "https://github.com/DevenPanchal/simpliflow-usage"




